Create separate threads on GitHub Discussions
oppia/stale-review-request-notifier pull request #5
Opened 2024-11-20 08:20 UTC by SD-13

Fixes #4 

I tested the changes in [my repo](https://github.com/SD-13/test-pending-review-notifier/discussions/categories/notify-reviewers2)

https://jam.dev/c/d9844463-3bd6-4c09-bc59-423dfed0b582

2024-11-20 10:55 UTC, seanlip requested changes
Hi @SD-13, I think this looks great, thanks for working on it so quickly!

I left a few inline comments. Just a few general notes:

- The jam.dev functionality looks good, but doesn't show what happens when you click into a discussion. Could you show it please?
- The CI checks are failing, might be worth taking a look at them.

Other than that, it looks really good to me ;) Thanks a lot!

2024-11-20 10:55 UTC, seanlip commented on .github/PENDING_REVIEW_NOTIFICATION_TEMPLATE.md
> +The following PRs are blocked on your review:
I think you'll still want to keep the "Hi {{username}}" bit, otherwise this is a bit abrupt?

Let's maybe also changed "blocked" here to "currently blocked".

2024-11-20 10:55 UTC, seanlip commented on .github/PENDING_REVIEW_NOTIFICATION_TEMPLATE.md
> -Please review and unassign yourself from the pending PRs as soon as possible.
Please keep this line, thanks. Let's also change it to: "Please review and unassign yourself from the pending PRs as soon as possible, then mark this discussion thread as 'Done'."

2024-11-20 10:55 UTC, seanlip commented on src/github_services.py
> +    """Delete all existing discussions"""
Delete all existing discussions in the given discussion category.

2024-11-20 10:55 UTC, seanlip commented on src/github_services.py
> +    """Create new discussion with given title and body."""
Create a new discussion with the given title and body in the given discussion category.

2024-11-20 10:55 UTC, seanlip commented on src/main.py
>          pr_list: str. List of PRs not reviewed within the maximum waiting time.
It's a bit odd that this is a string. Is it actually a string or is it a list?

If the former, maybe more info in the docstring about how this string is actually formatted would be helpful.

2024-11-20 10:55 UTC, seanlip commented on src/main.py
> +        discussion_body = generate_message('\n'.join(str(pr) for pr in pr_list), TEMPLATE_PATH)
Ah, the first arg here seems to be doing some joining. Maybe better to do that in the generate_message() function instead?

2024-11-21 18:28 UTC, SD-13 commented on .github/PENDING_REVIEW_NOTIFICATION_TEMPLATE.md
> +The following PRs are blocked on your review:
Updated.

2024-11-21 18:29 UTC, SD-13 commented on src/github_services.py
> +    """Delete all existing discussions"""
done

2024-11-21 18:29 UTC, SD-13 commented on src/github_services.py
> +    """Create new discussion with given title and body."""
done

2024-11-21 18:31 UTC, SD-13 commented on src/main.py
>          pr_list: str. List of PRs not reviewed within the maximum waiting time.
Now it is taking `PullRequest` objects as input and joining it to string inside the function.

2024-11-21 18:31 UTC, SD-13 commented on src/main.py
> +        discussion_body = generate_message('\n'.join(str(pr) for pr in pr_list), TEMPLATE_PATH)
Yes, now we are doing it inside the function.

2024-11-21 18:37 UTC, SD-13 commented on .github/PENDING_REVIEW_NOTIFICATION_TEMPLATE.md
> -Please review and unassign yourself from the pending PRs as soon as possible.
Added.

2024-11-22 02:18 UTC, seanlip reviewed
Thanks @SD-13 -- code looks fine to me generally with regards to the inline comments. Just need to fix the CI, and if you could add a demo video showing what going "into" a discussion thread looks like, that'd be great. Thanks!

2024-12-04 20:46 UTC, SD-13 commented
Hey @seanlip, here is a jam(https://jam.dev/c/d202211c-e4a0-476b-ba59-4409bdb6d225) of the discussions, you can also check out them here https://github.com/SD-13/test-pending-review-notifier/discussions/categories/notify-reviewers2.
(Note: While testing, I removed "@" from discussion body to avoid unnecessary ping)

Please review the changes when you get time. Thanks!

2024-12-05 17:49 UTC, seanlip approved these changes
Thanks @SD-13! No concerns from my end, and the proof looks good. Let's get this merged!

2024-12-05 17:49 UTC, merged

2024-12-05 17:53 UTC, seanlip commented
@SD-13 We need to get the stale notifier working on oppia/oppia as well. I'm making updates to the CI workflows on oppia/oppia in https://github.com/oppia/oppia/pull/21363 and I've included the update there -- see https://github.com/oppia/oppia/pull/21363/commits/3f7e63bf6161881e8f1d5a239f55e007785209bc .

Just FYI! The new workflow should start working when that PR is merged :)